apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "notes-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "notes-app.name" . }}
    spec:
      containers:
      - name: notes
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80

