apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: nginx:1.25   # (weâ€™ll replace with your image next)
        ports:
        - containerPort: 80
  envFrom:
    - secretRef:
        name: django-secrets
