{{- if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-green
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.green.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      color: green
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        color: green
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.green.image.tag }}"
        ports:
        - containerPort: 8000
{{- end }}
