{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      track: canary
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        track: canary
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.canary.image.tag }}"
        ports:
        - containerPort: 8000
{{- end }}
