apiVersion: v1
kind: Service
metadata:
  name: notes-app
spec:
  type: ClusterIP
  selector:
  app: {{ .Release.Name }}
  color: {{ .Values.traffic.color }}

  ports:
    - port: 80
      targetPort: 8000
