---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: django-secrets
  namespace: notes-app
spec:
  encryptedData:
    DB_PASSWORD: AgB9fyTE0Y+Z9uScL/I3bORPHJOuwNjBEb36cikoITt2y/pVqkkNZA01TH3tDrs2I1RGje/7NZILHY7UXiduIPms98W+j7btqb6c9HJz270/Gq+BWfPGaquOKInVlwQruE/3a/9X/WQcpRa7oNTh9Ddnr3GhlAxWHvMgLcRPm3WYQM6wpbYc9gzvtJO9jGxvCO3mI0r42d2/93qTfj0rISvG93avvCXvNBvMK9qAzLLMa9Q2nP1RmluMx5o/dY0ite0UmB7D/TUJTnDBaN8y/fzZMkcklrvJMcLFC49QDTO1pjuzoH5SNHrWRvNEoaLzcvbH52s76BX7VFp1qSoFeNYbaPXomk3VO85Prhp4J+9A7+9obkYFZqxXcpxDm80+83uGR5jSq3jiXJqAn8xT1MALeLSdtJjJAKZ7Vj/3PG3ARDZk1+oKl5b3n94ositYGoO7tIqgAIleDWUrxdj43YkaYkoxa1nXxReLTXmYhx4er9TtWe7qtK5iBH3PTNOjxt3RJZFhjbjMyTDPPsHD2UFLjYPmT+y4sy4nbB53ht5noXeI+BPxgKvn0hN41CH+dBuFZuhAQWXW4QJf2TsQsEwWJa7dSM5AaE2azafWX3vcdzL+YQoJnBtY6KO0yzY/5HbKXG8xsLMtGeqFv412t0BLBhSZdnNi4YC6l5vBtB3W1XAWEUYYNK3SsBhbz8ffWT7O71Q1gRaH
  template:
    metadata:
      name: django-secrets
      namespace: notes-app
