---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notes-secret
  namespace: notes-helm-dev
spec:
  encryptedData:
    DB_PASS: AgANsiGzThOIW8EkKUXdccPKfns1xVb6GsTK7ygajODLt1voW4V4yjTy72sYqTSSUaQqN/TzFdxDpt5BWtdBdO8cvsC2Ev/POyDheO2FSPMi2ToiCmcGJTez8Be7eAGufVRxuFI5Kwmp6EaFElYnoxqwTJFUeXEag7YZbOXYm+HGzgKWaDna0Og/Fn4+ql62tIwQAZi1kRVbtbGBc7VFY+c+ukuRbkH1eDs3YoqOZXk0pCdDnfnArhxRgO4MicS+6bK0dkOpZoZ+DAR6sy/Tmg+ZBnefmNUKsqcS9KTrHSYm8W3xCmvKWAwuLiaRU8fW6vZoVz78pWSjoYT10wfnSEXRhEjixInc1+Z+8FN5RejBBavOt3cnMQ3GGxqjbBRToKaeaW/VIrXMtso5kWAIDrmu+Qud2KN8ZrANFl+npSxsHuDpmlYmt+20Z1WYV93YqEFZAIx55NLaEAb3kv6y7mA766IWrQUBbLAYjmpr38xNXFvUnOPfUrYxtCi6Cdt4SJws5Dv8HomZT/RcJjmAxr+QPmTci03lcbyIeRHCUu75lkkk0weK0YJXyaVvDbK5VGvDQ4xBoVIASWK/5JIjCDK4iQdHiI+anIFQCp5Vs5dG91ZzcNcLjv5XAafUq7gkqwk5U+WLdQsb0pZXxL0MEHuA+fjtBBEQlj8TR7Z17DZ/vIlVMZ8+RxV3gzZ1X6bfepA2keysengDsB/DHQ==
    DB_USER: AgBeOx+rQOVvthCoE2vwjQSSgVSDF4PltvUwNzTm7EStAkoVYmxEI5v6bejwiEd2nRu70TrbsQgeJFJtAjm+X22X6Vh5BFzngnWl61GuDfoQNYLbxR0KUBgQBfCxy+y34D6zMvXsBvvARFCDitYFg4tchjOx5BQOXXNBpvudM+EiGvHZWkAcWTc1mfxxVxf99rdqJJTtkP7qvshPoFvHl7YI4yZVi8c61fXPaURRlDiVYvVK1yKgx6pOVfCx11wqIojPEpWwzVTml6tT2IO2vyasLi4V7+fWj8WjOhxji2qucK3Ygh4wA+Q4JtZWWuXzMZs7hcTVr6AoYjkf3vRm5QrlK5mIp8re3l7huvnGm077dGO556KlknHW9ILHvnkE6JKW2t3uWo5gaByIVN7f/K/oB3l7d1inGhl0B211rT8NUSI6+d69aISTVkgf3sXS4uw5WsCJIwkWBZHzPjWFVwWH8cutZ08/x6YcaVMdD3y5v6yXXUAgbBfBLizNwEv1t8l7EjkU1NMdN7XAO0076Xpo4MR2CjgK9FDyPJLmcWen0NsphGt0Z07nSOACapQVhPE8Emc7zr17P3rdOrTwTLh5ZeVj5IWgjlErTMq0N9wpD9tN4prKYi0mT3NaJPgKdxYROI4QxkhDsnSpgx9qV9ZzEbHdGLegKyMRV6g4f7q0izCd0uP7zQcHcfaCPW37nB16qMqqgQ==
  template:
    metadata:
      name: notes-secret
      namespace: notes-helm-dev
